apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "focusjam.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "focusjam.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: server
    helm.sh/chart:  {{ include "focusjam.chart" . }}
spec:
  {{- if not .Values.focusjamApp.autoscaling.enabled }}
  replicas: {{ .Values.focusjamApp.replicaCount }}
  {{- end }}
  {{- with .Values.focusjamApp.strategy }}
  strategy:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.focusjamApp.revisionHistoryLimit }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "focusjam.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "focusjam.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/component: server
        helm.sh/chart: {{ include "focusjam.chart" . }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.focusjamApp.service.metricsPort }}"
        prometheus.io/path: "/metrics"
        {{- if .Values.focusjamApp.extraPodAnnotations }}
        {{- .Values.focusjamApp.extraPodAnnotations | toYaml | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.focusjamApp.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.focusjamApp.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.focusjamApp.affinity }}
      affinity:
        {{- toYaml .Values.focusjamApp.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.focusjamApp.tolerations }}
      tolerations:
      {{- toYaml .Values.focusjamApp.tolerations | nindent 6 }}
      {{- end }}
      {{- if .Values.focusjamApp.securityContext }}
      securityContext:
        {{- toYaml .Values.focusjamApp.securityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      {{- if .Values.focusjamApp.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml .Values.focusjamApp.imagePullSecrets | nindent 6 }}
      {{- end }}
      {{- if .Values.focusjamApp.extraInitContainers }}
      initContainers:
      {{- .Values.focusjamApp.extraInitContainers | toYaml | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ include "focusjam.name" . }}
        image: "{{ .Values.focusjamApp.image.repository }}:{{ .Values.focusjamApp.image.tag }}"
        imagePullPolicy: {{ .Values.focusjamApp.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.focusjamApp.service.internalPort }}
          name: api
        - containerPort: {{ .Values.focusjamApp.service.metricsPort }}
          name: metrics
        - containerPort: {{ .Values.focusjamApp.service.clusterPort }}
          name: cluster
        - containerPort: {{ .Values.focusjamApp.service.gossipPort }}
          name: gossip
        env:
        - name: MM_CONFIG
          valueFrom:
            secretKeyRef:
           {{- if and .Values.global.features.database.existingDatabaseSecret .Values.global.features.database.existingDatabaseSecret.name }}
              name: {{ .Values.global.features.database.existingDatabaseSecret.name }}
              key: {{ .Values.global.features.database.existingDatabaseSecret.key }}
           {{- else }}
              name: {{ include "focusjam.fullname" . }}-focusjam-dbsecret
              key: focusjam.dbsecret
           {{- end }}
        - name: MM_SERVICESETTINGS_SITEURL
          value: "{{ .Values.global.siteUrl }}"
        - name: MM_SERVICESETTINGS_LISTENADDRESS
          value: ":{{ .Values.focusjamApp.service.internalPort }}"
{{- if .Values.global.features.jobserver.enabled }}
        - name: MM_JOBSETTINGS_RUNJOBS
          value: "false"
        - name: MM_JOBSETTINGS_RUNSCHEDULER
          value: "false"
{{- end }}
{{- if eq .Values.global.features.fileStore.driver "amazons3" }}
        - name: MM_FILESETTINGS_DRIVERNAME
          value: "amazons3"
        - name: MM_FILESETTINGS_AMAZONS3BUCKET
          value: "{{ .Values.global.features.fileStore.bucket }}"
        {{- if .Values.global.features.fileStore.region }}
        - name: MM_FILESETTINGS_AMAZONS3REGION
          value: "{{ .Values.global.features.fileStore.region }}"
        {{- end }}
        {{- if .Values.global.features.fileStore.url }}
        - name: MM_FILESETTINGS_AMAZONS3ENDPOINT
          value: "{{ .Values.global.features.fileStore.url }}"
        - name: MM_FILESETTINGS_AMAZONS3SSL
          value: "true"
        {{- end }}
        {{- if .Values.global.features.fileStore.existingSecret.name }}
        - name: MM_FILESETTINGS_AMAZONS3ACCESSKEYID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.features.fileStore.existingSecret.name }}
              key: {{ .Values.global.features.fileStore.existingSecret.accessKeyIdKey }}
        - name: MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.features.fileStore.existingSecret.name }}
              key: {{ .Values.global.features.fileStore.existingSecret.secretAccessKeyKey }}
        {{- else if .Values.global.features.fileStore.accessKeyId }}
        - name: MM_FILESETTINGS_AMAZONS3ACCESSKEYID
          value: "{{ .Values.global.features.fileStore.accessKeyId }}"
        - name: MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY
          value: "{{ .Values.global.features.fileStore.secretAccessKey }}"
        {{- end }}
{{- end }}
{{- with .Values.focusjamApp.extraEnv }}
{{ toYaml . | indent 8 }}
{{- end }}
        {{- with .Values.focusjamApp.envFrom }}
        envFrom:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        livenessProbe:
          initialDelaySeconds: 90
          timeoutSeconds: 5
          periodSeconds: 15
          httpGet:
            path: /api/v4/system/ping
            port: {{ .Values.focusjamApp.service.internalPort }}
        readinessProbe:
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 15
          httpGet:
            path: /api/v4/system/ping
            port: {{ .Values.focusjamApp.service.internalPort }}
        volumeMounts:
        {{- if .Values.global.existingLicenseSecret.name }}
        - mountPath: /mattermost/{{.Values.global.existingLicenseSecret.key }}
          name: mattermost-license
          subPath: {{.Values.global.existingLicenseSecret.key }}
        {{- else }}
        - mountPath: /mattermost/mattermost.mattermost-license
          name: mattermost-license
          subPath: focusjam.mattermost-license
        {{- end }}
        - mountPath: /mattermost/plugins/
          name: mattermost-plugins
        - mountPath: /mattermost/client/plugins/
          name: mattermost-plugins-client
{{- if .Values.focusjamApp.extraVolumeMounts }}
{{ toYaml .Values.focusjamApp.extraVolumeMounts | indent 8 }}
{{- end }}
        resources:
{{ toYaml .Values.focusjamApp.resources | indent 10 }}
      volumes:
      - name: mattermost-plugins
        emptyDir: {}
      - name: mattermost-plugins-client
        emptyDir: {}
      - name: mattermost-config
        emptyDir: {}
      - name: mattermost-license
        secret:
          {{- if .Values.global.existingLicenseSecret.name }}
          secretName: {{ .Values.global.existingLicenseSecret.name }}
          {{- else }}
          secretName: {{ include "focusjam.fullname" . }}-mattermost-license
          {{- end }}
{{- if .Values.focusjamApp.extraVolumes }}
{{ toYaml .Values.focusjamApp.extraVolumes | indent 6 }}
{{- end }}
