{{- if not (and .Values.global.features.database.existingDatabaseSecret .Values.global.features.database.existingDatabaseSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "focusjam.fullname" . }}-focusjam-dbsecret
  labels:
    app.kubernetes.io/name: {{ include "focusjam.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart:  {{ include "focusjam.chart" . }}
type: Opaque
data:
  focusjam.dbsecret: {{ .Values.global.features.database.dataSource | b64enc }}
{{- end }}
