{{- if .Values.global.features.jobserver.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "focustalk.jobserver.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "focustalk.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ .Values.global.features.jobserver.name }}
    helm.sh/chart:  {{ include "focustalk.chart" . }}
spec:
  replicas: {{ .Values.global.features.jobserver.replicaCount }}
  {{- with .Values.global.features.jobserver.strategy }}
  strategy:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.global.features.jobserver.revisionHistoryLimit }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "focustalk.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/component: {{ .Values.global.features.jobserver.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "focustalk.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/component: {{ .Values.global.features.jobserver.name }}
        helm.sh/chart: {{ include "focustalk.chart" . }}
      annotations:
        {{- if .Values.focustalkApp.extraPodAnnotations }}
        {{- .Values.focustalkApp.extraPodAnnotations | toYaml | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.global.features.jobserver.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.global.features.jobserver.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.global.features.jobserver.affinity }}
      affinity:
        {{- toYaml .Values.global.features.jobserver.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.global.features.jobserver.tolerations }}
      tolerations:
      {{- toYaml .Values.global.features.jobserver.tolerations | nindent 6 }}
      {{- end }}
      {{- if .Values.focustalkApp.securityContext }}
      securityContext:
        {{- toYaml .Values.focustalkApp.securityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.focustalkApp.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml .Values.focustalkApp.imagePullSecrets | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ include "focustalk.name" . }}-jobserver
        image: "{{ .Values.focustalkApp.image.repository }}:{{ .Values.focustalkApp.image.tag }}"
        imagePullPolicy: {{ .Values.focustalkApp.image.pullPolicy }}
        command: ["mattermost", "jobserver"]
        env:
        - name: MM_CONFIG
          valueFrom:
            secretKeyRef:
           {{- if and .Values.global.features.database.existingDatabaseSecret .Values.global.features.database.existingDatabaseSecret.name }}
              name: {{ .Values.global.features.database.existingDatabaseSecret.name }}
              key: {{ .Values.global.features.database.existingDatabaseSecret.key }}
           {{- else }}
              name: {{ include "focustalk.fullname" . }}-focustalk-dbsecret
              key: focustalk.dbsecret
           {{- end }}
        {{- with .Values.global.features.jobserver.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        {{- if .Values.global.existingLicenseSecret.name }}
        - mountPath: /mattermost/{{.Values.global.existingLicenseSecret.key }}
          name: mattermost-license
          subPath: {{.Values.global.existingLicenseSecret.key }}
        {{- else }}
        - mountPath: /mattermost/mattermost.mattermost-license
          name: mattermost-license
          subPath: focustalk.mattermost-license
        {{- end }}
      volumes:
      - name: mattermost-license
        secret:
          {{- if .Values.global.existingLicenseSecret.name }}
          secretName: {{ .Values.global.existingLicenseSecret.name }}
          {{- else }}
          secretName: {{ include "focustalk.fullname" . }}-mattermost-license
          {{- end }}

{{- end -}}
