{{- if .Values.focustalkApp.ingress.enabled -}}
{{- $serviceName := include "focustalk.fullname" . -}}
{{- $servicePort := .Values.focustalkApp.service.externalPort -}}
apiVersion: {{ include "focustalk.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "focustalk.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "focustalk.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart:  {{ include "focustalk.chart" . }}
  annotations:
    {{- if .Values.focustalkApp.ingress.annotations }}
{{ toYaml .Values.focustalkApp.ingress.annotations | indent 4 }}
    {{- end }}
    {{- if .Values.focustalkApp.ingress.tls }}
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
spec:
  {{- if .Values.focustalkApp.ingress.ingressClassName }}
  ingressClassName: {{ .Values.focustalkApp.ingress.ingressClassName }}
  {{- end }}
  rules:
  {{- range $host := .Values.focustalkApp.ingress.hosts }}
  - host: {{ $host }}
    http:
      paths:
      - path: /
        {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
        backend:
          service:
            name: {{ $serviceName }}
            port:
              number: {{ $servicePort }}
        pathType: Prefix
        {{- else }}
        backend:
          serviceName: {{ $serviceName }}
          servicePort: {{ $servicePort }}
        {{- end }}
  {{- end -}}
  {{- if .Values.focustalkApp.ingress.tls }}
  tls:
{{ toYaml .Values.focustalkApp.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
