{{- if not (and .Values.global.features.database.existingDatabaseSecret .Values.global.features.database.existingDatabaseSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "focustalk.fullname" . }}-focustalk-dbsecret
  labels:
    app.kubernetes.io/name: {{ include "focustalk.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart:  {{ include "focustalk.chart" . }}
type: Opaque
data:
  focustalk.dbsecret: {{ .Values.global.features.database.dataSource | b64enc }}
{{- end }}