apiVersion: v1
kind: Service
metadata:
  name: {{ include "mattermost.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mattermost.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart:  {{ include "mattermost.chart" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "mattermost.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: server
  type: {{ .Values.focustalkApp.service.type }}
  ports:
  - port: {{ .Values.focustalkApp.service.externalPort }}
    targetPort: {{ .Values.focustalkApp.service.internalPort }}
    protocol: TCP
    name: {{ .Values.focustalkApp.service.name }}
  - port: {{ .Values.focustalkApp.service.metricsPort }}
    targetPort: {{ .Values.focustalkApp.service.metricsPort }}
    protocol: TCP
    name: {{ .Values.focustalkApp.service.metricsName }}
  - port: {{ .Values.focustalkApp.service.clusterPort }}
    targetPort: {{ .Values.focustalkApp.service.clusterPort }}
    protocol: TCP
    name: cluster
  - port: {{ .Values.focustalkApp.service.gossipPort }}
    targetPort: {{ .Values.focustalkApp.service.gossipPort }}
    protocol: TCP
    name: gossip
